version: '3.6'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
      - influxdb_cfg:/etc/influxdb2

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 9000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    links:
      - influxdb

volumes:        
  influxdb_data:
    external: true
  influxdb_cfg:
    external: true
  grafana_data:
    external: true
